# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 2477288291e22943d290b24e7ea7f1bd8f74a421

{
  "title": "Стол IKEA",
  "description": "Возможен торг"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token e279be90f87ec7692ca69721aed8ad7886301af7

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2022-12-01
Content-Type: application/json
